/* THIS FILE WAS AUTOGENERATED BY PAYLOAD. IT WILL CHANGE WHEN YOU RUN payload generate:importmap */
import config from "@payload-config"
import "@payloadcms/next/css"
import type { ServerFunctionClient } from "payload"
import { handleServerFunctions, RootLayout } from "@payloadcms/next/layouts"
import React from "react"
import { importMap } from "./admin/importMap.js"

type Args = {
  children: React.ReactNode
}

const serverFunction: ServerFunctionClient = async function (args) {
  "use server"
  return handleServerFunctions({
    ...args,
    config,
    importMap,
  })
}

// This is Payload's own root layout for the /admin and Payload /api branch
// (see the (payload) route group) — separate from the storefront's root
// layout in (storefront)/layout.tsx. Next.js's "multiple root layouts"
// pattern is what makes this possible: there is no layout.tsx directly in
// src/app itself, only inside each top-level route group, so each gets its
// own <html>/<body> without nesting one inside the other.
const Layout = ({ children }: Args) => (
  <RootLayout config={config} importMap={importMap} serverFunction={serverFunction}>
    {children}
  </RootLayout>
)

export default Layout
