/* THIS FILE WAS AUTOGENERATED BY PAYLOAD. IT WILL CHANGE WHEN YOU RUN payload generate:importmap */
import config from "@payload-config"
import { GRAPHQL_POST } from "@payloadcms/next/routes"

export const POST = GRAPHQL_POST(config)
