/* THIS FILE WAS AUTOGENERATED BY PAYLOAD. IT WILL CHANGE WHEN YOU RUN payload generate:importmap */
import config from "@payload-config"
import { GRAPHQL_PLAYGROUND_GET } from "@payloadcms/next/routes"

export const GET = GRAPHQL_PLAYGROUND_GET(config)
